from qiskit import QuantumCircuit, QuantumRegister
import numpy as np

def adder20():
    qc = QuantumCircuit()

    q = QuantumRegister(20, 'q')

    qc.add_register(q)

    qc.cx(q[2], q[1])
    qc.cx(q[4], q[3])
    qc.cx(q[6], q[5])
    qc.cx(q[8], q[7])
    qc.cx(q[10], q[9])
    qc.cx(q[12], q[11])
    qc.cx(q[14], q[13])
    qc.cx(q[16], q[15])
    qc.cx(q[18], q[17])
    qc.cx(q[2], q[0])
    qc.h(q[2])
    qc.cx(q[1], q[2])
    qc.tdg(q[2])
    qc.cx(q[0], q[2])
    qc.t(q[2])
    qc.cx(q[1], q[2])
    qc.t(q[1])
    qc.tdg(q[2])
    qc.cx(q[0], q[2])
    qc.cx(q[0], q[1])
    qc.t(q[2])
    qc.t(q[0])
    qc.tdg(q[1])
    qc.h(q[2])
    qc.cx(q[0], q[1])
    qc.cx(q[4], q[2])
    qc.x(q[1])
    qc.h(q[4])
    qc.cx(q[0], q[1])
    qc.cx(q[3], q[4])
    qc.tdg(q[4])
    qc.cx(q[2], q[4])
    qc.t(q[4])
    qc.cx(q[3], q[4])
    qc.t(q[3])
    qc.tdg(q[4])
    qc.cx(q[2], q[4])
    qc.cx(q[2], q[3])
    qc.t(q[4])
    qc.t(q[2])
    qc.tdg(q[3])
    qc.h(q[4])
    qc.cx(q[2], q[3])
    qc.cx(q[6], q[4])
    qc.x(q[3])
    qc.h(q[6])
    qc.cx(q[2], q[3])
    qc.cx(q[5], q[6])
    qc.tdg(q[6])
    qc.cx(q[4], q[6])
    qc.t(q[6])
    qc.cx(q[5], q[6])
    qc.t(q[5])
    qc.tdg(q[6])
    qc.cx(q[4], q[6])
    qc.cx(q[4], q[5])
    qc.t(q[6])
    qc.t(q[4])
    qc.tdg(q[5])
    qc.h(q[6])
    qc.cx(q[4], q[5])
    qc.cx(q[8], q[6])
    qc.x(q[5])
    qc.h(q[8])
    qc.cx(q[4], q[5])
    qc.cx(q[7], q[8])
    qc.tdg(q[8])
    qc.cx(q[6], q[8])
    qc.t(q[8])
    qc.cx(q[7], q[8])
    qc.t(q[7])
    qc.tdg(q[8])
    qc.cx(q[6], q[8])
    qc.cx(q[6], q[7])
    qc.t(q[8])
    qc.t(q[6])
    qc.tdg(q[7])
    qc.h(q[8])
    qc.cx(q[6], q[7])
    qc.cx(q[10], q[8])
    qc.x(q[7])
    qc.h(q[10])
    qc.cx(q[6], q[7])
    qc.cx(q[9], q[10])
    qc.tdg(q[10])
    qc.cx(q[8], q[10])
    qc.t(q[10])
    qc.cx(q[9], q[10])
    qc.t(q[9])
    qc.tdg(q[10])
    qc.cx(q[8], q[10])
    qc.cx(q[8], q[9])
    qc.t(q[10])
    qc.t(q[8])
    qc.tdg(q[9])
    qc.h(q[10])
    qc.cx(q[8], q[9])
    qc.cx(q[12], q[10])
    qc.x(q[9])
    qc.h(q[12])
    qc.cx(q[8], q[9])
    qc.cx(q[11], q[12])
    qc.tdg(q[12])
    qc.cx(q[10], q[12])
    qc.t(q[12])
    qc.cx(q[11], q[12])
    qc.t(q[11])
    qc.tdg(q[12])
    qc.cx(q[10], q[12])
    qc.cx(q[10], q[11])
    qc.t(q[12])
    qc.t(q[10])
    qc.tdg(q[11])
    qc.h(q[12])
    qc.cx(q[10], q[11])
    qc.cx(q[14], q[12])
    qc.x(q[11])
    qc.h(q[14])
    qc.cx(q[10], q[11])
    qc.cx(q[13], q[14])
    qc.tdg(q[14])
    qc.cx(q[12], q[14])
    qc.t(q[14])
    qc.cx(q[13], q[14])
    qc.t(q[13])
    qc.tdg(q[14])
    qc.cx(q[12], q[14])
    qc.cx(q[12], q[13])
    qc.t(q[14])
    qc.t(q[12])
    qc.tdg(q[13])
    qc.h(q[14])
    qc.cx(q[12], q[13])
    qc.cx(q[16], q[14])
    qc.x(q[13])
    qc.h(q[16])
    qc.cx(q[12], q[13])
    qc.cx(q[15], q[16])
    qc.tdg(q[16])
    qc.cx(q[14], q[16])
    qc.t(q[16])
    qc.cx(q[15], q[16])
    qc.t(q[15])
    qc.tdg(q[16])
    qc.cx(q[14], q[16])
    qc.cx(q[14], q[15])
    qc.t(q[16])
    qc.t(q[14])
    qc.tdg(q[15])
    qc.h(q[16])
    qc.cx(q[14], q[15])
    qc.cx(q[18], q[16])
    qc.x(q[15])
    qc.h(q[18])
    qc.cx(q[14], q[15])
    qc.cx(q[17], q[18])
    qc.tdg(q[18])
    qc.cx(q[16], q[18])
    qc.t(q[18])
    qc.cx(q[17], q[18])
    qc.t(q[17])
    qc.tdg(q[18])
    qc.cx(q[16], q[18])
    qc.cx(q[16], q[17])
    qc.t(q[18])
    qc.t(q[16])
    qc.tdg(q[17])
    qc.h(q[18])
    qc.cx(q[16], q[17])
    qc.cx(q[18], q[19])
    qc.x(q[17])
    qc.h(q[18])
    qc.cx(q[16], q[17])
    qc.cx(q[17], q[18])
    qc.tdg(q[18])
    qc.cx(q[16], q[18])
    qc.t(q[18])
    qc.cx(q[17], q[18])
    qc.t(q[17])
    qc.tdg(q[18])
    qc.cx(q[16], q[18])
    qc.cx(q[16], q[17])
    qc.t(q[18])
    qc.t(q[16])
    qc.tdg(q[17])
    qc.h(q[18])
    qc.cx(q[16], q[17])
    qc.x(q[17])
    qc.cx(q[18], q[16])
    qc.h(q[16])
    qc.cx(q[18], q[17])
    qc.cx(q[15], q[16])
    qc.tdg(q[16])
    qc.cx(q[14], q[16])
    qc.t(q[16])
    qc.cx(q[15], q[16])
    qc.t(q[15])
    qc.tdg(q[16])
    qc.cx(q[14], q[16])
    qc.cx(q[14], q[15])
    qc.t(q[16])
    qc.t(q[14])
    qc.tdg(q[15])
    qc.h(q[16])
    qc.cx(q[14], q[15])
    qc.x(q[15])
    qc.cx(q[16], q[14])
    qc.h(q[14])
    qc.cx(q[16], q[15])
    qc.cx(q[13], q[14])
    qc.tdg(q[14])
    qc.cx(q[12], q[14])
    qc.t(q[14])
    qc.cx(q[13], q[14])
    qc.t(q[13])
    qc.tdg(q[14])
    qc.cx(q[12], q[14])
    qc.cx(q[12], q[13])
    qc.t(q[14])
    qc.t(q[12])
    qc.tdg(q[13])
    qc.h(q[14])
    qc.cx(q[12], q[13])
    qc.x(q[13])
    qc.cx(q[14], q[12])
    qc.h(q[12])
    qc.cx(q[14], q[13])
    qc.cx(q[11], q[12])
    qc.tdg(q[12])
    qc.cx(q[10], q[12])
    qc.t(q[12])
    qc.cx(q[11], q[12])
    qc.t(q[11])
    qc.tdg(q[12])
    qc.cx(q[10], q[12])
    qc.cx(q[10], q[11])
    qc.t(q[12])
    qc.t(q[10])
    qc.tdg(q[11])
    qc.h(q[12])
    qc.cx(q[10], q[11])
    qc.x(q[11])
    qc.cx(q[12], q[10])
    qc.h(q[10])
    qc.cx(q[12], q[11])
    qc.cx(q[9], q[10])
    qc.tdg(q[10])
    qc.cx(q[8], q[10])
    qc.t(q[10])
    qc.cx(q[9], q[10])
    qc.t(q[9])
    qc.tdg(q[10])
    qc.cx(q[8], q[10])
    qc.cx(q[8], q[9])
    qc.t(q[10])
    qc.t(q[8])
    qc.tdg(q[9])
    qc.h(q[10])
    qc.cx(q[8], q[9])
    qc.x(q[9])
    qc.cx(q[10], q[8])
    qc.h(q[8])
    qc.cx(q[10], q[9])
    qc.cx(q[7], q[8])
    qc.tdg(q[8])
    qc.cx(q[6], q[8])
    qc.t(q[8])
    qc.cx(q[7], q[8])
    qc.t(q[7])
    qc.tdg(q[8])
    qc.cx(q[6], q[8])
    qc.cx(q[6], q[7])
    qc.t(q[8])
    qc.t(q[6])
    qc.tdg(q[7])
    qc.h(q[8])
    qc.cx(q[6], q[7])
    qc.x(q[7])
    qc.cx(q[8], q[6])
    qc.h(q[6])
    qc.cx(q[8], q[7])
    qc.cx(q[5], q[6])
    qc.tdg(q[6])
    qc.cx(q[4], q[6])
    qc.t(q[6])
    qc.cx(q[5], q[6])
    qc.t(q[5])
    qc.tdg(q[6])
    qc.cx(q[4], q[6])
    qc.cx(q[4], q[5])
    qc.t(q[6])
    qc.t(q[4])
    qc.tdg(q[5])
    qc.h(q[6])
    qc.cx(q[4], q[5])
    qc.x(q[5])
    qc.cx(q[6], q[4])
    qc.h(q[4])
    qc.cx(q[6], q[5])
    qc.cx(q[3], q[4])
    qc.tdg(q[4])
    qc.cx(q[2], q[4])
    qc.t(q[4])
    qc.cx(q[3], q[4])
    qc.t(q[3])
    qc.tdg(q[4])
    qc.cx(q[2], q[4])
    qc.cx(q[2], q[3])
    qc.t(q[4])
    qc.t(q[2])
    qc.tdg(q[3])
    qc.h(q[4])
    qc.cx(q[2], q[3])
    qc.x(q[3])
    qc.cx(q[4], q[2])
    qc.h(q[2])
    qc.cx(q[4], q[3])
    qc.cx(q[1], q[2])
    qc.tdg(q[2])
    qc.cx(q[0], q[2])
    qc.t(q[2])
    qc.cx(q[1], q[2])
    qc.t(q[1])
    qc.tdg(q[2])
    qc.cx(q[0], q[2])
    qc.cx(q[0], q[1])
    qc.t(q[2])
    qc.t(q[0])
    qc.tdg(q[1])
    qc.h(q[2])
    qc.cx(q[0], q[1])
    qc.x(q[1])
    qc.cx(q[2], q[0])
    qc.cx(q[2], q[1])
    return qc

def adder20_0():
    qc = QuantumCircuit()

    q = QuantumRegister(12, 'q')

    qc.add_register(q)

    qc.cx(q[2], q[1])
    qc.cx(q[4], q[3])
    qc.cx(q[6], q[5])
    qc.cx(q[8], q[7])
    qc.cx(q[10], q[9])
    qc.h(q[11])
    qc.cx(q[2], q[0])
    qc.h(q[2])
    qc.cx(q[1], q[2])
    qc.tdg(q[2])
    qc.cx(q[0], q[2])
    qc.t(q[2])
    qc.cx(q[1], q[2])
    qc.t(q[1])
    qc.tdg(q[2])
    qc.cx(q[0], q[2])
    qc.cx(q[0], q[1])
    qc.t(q[2])
    qc.t(q[0])
    qc.tdg(q[1])
    qc.h(q[2])
    qc.cx(q[0], q[1])
    qc.cx(q[4], q[2])
    qc.x(q[1])
    qc.h(q[4])
    qc.cx(q[0], q[1])
    qc.cx(q[3], q[4])
    qc.tdg(q[4])
    qc.cx(q[2], q[4])
    qc.t(q[4])
    qc.cx(q[3], q[4])
    qc.t(q[3])
    qc.tdg(q[4])
    qc.cx(q[2], q[4])
    qc.cx(q[2], q[3])
    qc.t(q[4])
    qc.t(q[2])
    qc.tdg(q[3])
    qc.h(q[4])
    qc.cx(q[2], q[3])
    qc.cx(q[6], q[4])
    qc.x(q[3])
    qc.h(q[6])
    qc.cx(q[2], q[3])
    qc.cx(q[5], q[6])
    qc.tdg(q[6])
    qc.cx(q[4], q[6])
    qc.t(q[6])
    qc.cx(q[5], q[6])
    qc.t(q[5])
    qc.tdg(q[6])
    qc.cx(q[4], q[6])
    qc.cx(q[4], q[5])
    qc.t(q[6])
    qc.t(q[4])
    qc.tdg(q[5])
    qc.h(q[6])
    qc.cx(q[4], q[5])
    qc.cx(q[8], q[6])
    qc.x(q[5])
    qc.h(q[8])
    qc.cx(q[4], q[5])
    qc.cx(q[7], q[8])
    qc.tdg(q[8])
    qc.cx(q[6], q[8])
    qc.t(q[8])
    qc.cx(q[7], q[8])
    qc.t(q[7])
    qc.tdg(q[8])
    qc.cx(q[6], q[8])
    qc.cx(q[6], q[7])
    qc.t(q[8])
    qc.t(q[6])
    qc.tdg(q[7])
    qc.h(q[8])
    qc.cx(q[6], q[7])
    qc.cx(q[10], q[8])
    qc.x(q[7])
    qc.h(q[10])
    qc.cx(q[6], q[7])
    qc.cx(q[9], q[10])
    qc.tdg(q[10])
    qc.cx(q[8], q[10])
    qc.t(q[10])
    qc.cx(q[9], q[10])
    qc.tdg(q[10])
    qc.cx(q[8], q[10])
    qc.t(q[9])
    qc.t(q[10])
    qc.cx(q[8], q[9])
    qc.t(q[8])
    qc.tdg(q[9])
    qc.cx(q[8], q[9])
    qc.x(q[9])
    qc.cx(q[8], q[9])
    qc.cx(q[9], q[11])
    qc.tdg(q[11])
    qc.cx(q[8], q[11])
    qc.t(q[11])
    qc.cx(q[9], q[11])
    qc.tdg(q[11])
    qc.cx(q[8], q[11])
    qc.t(q[9])
    qc.t(q[11])
    qc.cx(q[8], q[9])
    qc.h(q[11])
    qc.t(q[8])
    qc.tdg(q[9])
    qc.cx(q[8], q[9])
    qc.cx(q[11], q[8])
    qc.h(q[8])
    qc.x(q[9])
    qc.cx(q[7], q[8])
    qc.cx(q[11], q[9])
    qc.tdg(q[8])
    qc.cx(q[6], q[8])
    qc.t(q[8])
    qc.cx(q[7], q[8])
    qc.t(q[7])
    qc.tdg(q[8])
    qc.cx(q[6], q[8])
    qc.cx(q[6], q[7])
    qc.t(q[8])
    qc.t(q[6])
    qc.tdg(q[7])
    qc.h(q[8])
    qc.cx(q[6], q[7])
    qc.x(q[7])
    qc.cx(q[8], q[6])
    qc.h(q[6])
    qc.cx(q[8], q[7])
    qc.cx(q[5], q[6])
    qc.tdg(q[6])
    qc.cx(q[4], q[6])
    qc.t(q[6])
    qc.cx(q[5], q[6])
    qc.t(q[5])
    qc.tdg(q[6])
    qc.cx(q[4], q[6])
    qc.cx(q[4], q[5])
    qc.t(q[6])
    qc.t(q[4])
    qc.tdg(q[5])
    qc.h(q[6])
    qc.cx(q[4], q[5])
    qc.x(q[5])
    qc.cx(q[6], q[4])
    qc.h(q[4])
    qc.cx(q[6], q[5])
    qc.cx(q[3], q[4])
    qc.tdg(q[4])
    qc.cx(q[2], q[4])
    qc.t(q[4])
    qc.cx(q[3], q[4])
    qc.t(q[3])
    qc.tdg(q[4])
    qc.cx(q[2], q[4])
    qc.cx(q[2], q[3])
    qc.t(q[4])
    qc.t(q[2])
    qc.tdg(q[3])
    qc.h(q[4])
    qc.cx(q[2], q[3])
    qc.x(q[3])
    qc.cx(q[4], q[2])
    qc.h(q[2])
    qc.cx(q[4], q[3])
    qc.cx(q[1], q[2])
    qc.tdg(q[2])
    qc.cx(q[0], q[2])
    qc.t(q[2])
    qc.cx(q[1], q[2])
    qc.t(q[1])
    qc.tdg(q[2])
    qc.cx(q[0], q[2])
    qc.cx(q[0], q[1])
    qc.t(q[2])
    qc.t(q[0])
    qc.tdg(q[1])
    qc.h(q[2])
    qc.cx(q[0], q[1])
    qc.x(q[1])
    qc.cx(q[2], q[0])
    qc.cx(q[2], q[1])
    return qc

def adder20_1():
    qc = QuantumCircuit()

    q = QuantumRegister(10, 'q')

    qc.add_register(q)

    qc.h(q[0])
    qc.cx(q[2], q[1])
    qc.cx(q[4], q[3])
    qc.cx(q[6], q[5])
    qc.cx(q[8], q[7])
    qc.cx(q[2], q[0])
    qc.h(q[2])
    qc.cx(q[1], q[2])
    qc.tdg(q[2])
    qc.cx(q[0], q[2])
    qc.t(q[2])
    qc.cx(q[1], q[2])
    qc.t(q[1])
    qc.tdg(q[2])
    qc.cx(q[0], q[2])
    qc.cx(q[0], q[1])
    qc.t(q[2])
    qc.t(q[0])
    qc.tdg(q[1])
    qc.h(q[2])
    qc.cx(q[0], q[1])
    qc.cx(q[4], q[2])
    qc.x(q[1])
    qc.h(q[4])
    qc.cx(q[0], q[1])
    qc.cx(q[3], q[4])
    qc.tdg(q[4])
    qc.cx(q[2], q[4])
    qc.t(q[4])
    qc.cx(q[3], q[4])
    qc.t(q[3])
    qc.tdg(q[4])
    qc.cx(q[2], q[4])
    qc.cx(q[2], q[3])
    qc.t(q[4])
    qc.t(q[2])
    qc.tdg(q[3])
    qc.h(q[4])
    qc.cx(q[2], q[3])
    qc.cx(q[6], q[4])
    qc.x(q[3])
    qc.h(q[6])
    qc.cx(q[2], q[3])
    qc.cx(q[5], q[6])
    qc.tdg(q[6])
    qc.cx(q[4], q[6])
    qc.t(q[6])
    qc.cx(q[5], q[6])
    qc.t(q[5])
    qc.tdg(q[6])
    qc.cx(q[4], q[6])
    qc.cx(q[4], q[5])
    qc.t(q[6])
    qc.t(q[4])
    qc.tdg(q[5])
    qc.h(q[6])
    qc.cx(q[4], q[5])
    qc.cx(q[8], q[6])
    qc.x(q[5])
    qc.h(q[8])
    qc.cx(q[4], q[5])
    qc.cx(q[7], q[8])
    qc.tdg(q[8])
    qc.cx(q[6], q[8])
    qc.t(q[8])
    qc.cx(q[7], q[8])
    qc.t(q[7])
    qc.tdg(q[8])
    qc.cx(q[6], q[8])
    qc.cx(q[6], q[7])
    qc.t(q[8])
    qc.t(q[6])
    qc.tdg(q[7])
    qc.h(q[8])
    qc.cx(q[6], q[7])
    qc.cx(q[8], q[9])
    qc.x(q[7])
    qc.h(q[8])
    qc.cx(q[6], q[7])
    qc.cx(q[7], q[8])
    qc.tdg(q[8])
    qc.cx(q[6], q[8])
    qc.t(q[8])
    qc.cx(q[7], q[8])
    qc.t(q[7])
    qc.tdg(q[8])
    qc.cx(q[6], q[8])
    qc.cx(q[6], q[7])
    qc.t(q[8])
    qc.t(q[6])
    qc.tdg(q[7])
    qc.h(q[8])
    qc.cx(q[6], q[7])
    qc.x(q[7])
    qc.cx(q[8], q[6])
    qc.h(q[6])
    qc.cx(q[8], q[7])
    qc.cx(q[5], q[6])
    qc.tdg(q[6])
    qc.cx(q[4], q[6])
    qc.t(q[6])
    qc.cx(q[5], q[6])
    qc.t(q[5])
    qc.tdg(q[6])
    qc.cx(q[4], q[6])
    qc.cx(q[4], q[5])
    qc.t(q[6])
    qc.t(q[4])
    qc.tdg(q[5])
    qc.h(q[6])
    qc.cx(q[4], q[5])
    qc.x(q[5])
    qc.cx(q[6], q[4])
    qc.h(q[4])
    qc.cx(q[6], q[5])
    qc.cx(q[3], q[4])
    qc.tdg(q[4])
    qc.cx(q[2], q[4])
    qc.t(q[4])
    qc.cx(q[3], q[4])
    qc.t(q[3])
    qc.tdg(q[4])
    qc.cx(q[2], q[4])
    qc.cx(q[2], q[3])
    qc.t(q[4])
    qc.t(q[2])
    qc.tdg(q[3])
    qc.h(q[4])
    qc.cx(q[2], q[3])
    qc.x(q[3])
    qc.cx(q[4], q[2])
    qc.h(q[2])
    qc.cx(q[4], q[3])
    qc.cx(q[1], q[2])
    qc.tdg(q[2])
    qc.cx(q[0], q[2])
    qc.t(q[2])
    qc.cx(q[1], q[2])
    qc.t(q[1])
    qc.tdg(q[2])
    qc.cx(q[0], q[2])
    qc.cx(q[0], q[1])
    qc.t(q[2])
    qc.t(q[0])
    qc.tdg(q[1])
    qc.h(q[2])
    qc.cx(q[0], q[1])
    qc.x(q[1])
    qc.cx(q[2], q[0])
    qc.cx(q[2], q[1])
    return qc

